apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjoge30sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4IiwKCSJhdXRocyI6IHsKCQkJCSJnaGNyLmlvIjogewoJCQkJCSJhdXRoIjogIloyRnRkVHBuYUhCZmEweFROVGt5VFV4WFNrNVRia296V0VOYVRteEdjV1U1Y1hrelVqaHdNSEJKTm5CUUNnPT0iIAogICAgICAgICAgICAJfQogICAgICAgIH0KfQ==
type: kubernetes.io/dockerconfigjson
